messages:
  balance: "&a&l(!) &aYou currently have %amount% MobCoins(s)!"
  balance-other: "&a&l(!) &a%player% currently has %amount% MobCoin(s)!"
  gave-mobcoins: "&a&l(!) &aSuccessfully gave %player% %amount% MobCoins(s)!"
  paid-player: "&a&l(!) &aSuccessfully paid %player% %amount% MobCoins(s)!"
  removed-mobcoins: "&a&l(!) &aSuccessfully removed %amount% MobCoins(s) from %player%!"
  invalid-player: "&c&l(!) &cInvalid player!"
  not-enough-mobcoins: "&c&l(!) &cYou do not have enough MobCoins!"
  received-mobcoins: "&a&l+1 MobCoin &7(Grinding Mobs)"
  invalid-amount: "&c&l(!) &cYou specified an invalid amount!"
  no-permission: "&c&l(!) &cYou do not have permission to execute that command!"
  pay-negative: "&c&l(!) &cYou cannot pay a negative amount of MobCoins!"
settings:
  amount-per-mob: 1 # The amount of mob coins each mob will drop
mobs: # Chances of a MobCoin dropping when specified mob is killed
  ZOMBIE: 5
  SKELETON: 5
inventory:
  inventory-size: 45 # Must be a multiple of 9
  menu:
    default-reward:
      display-name: "&e&lDefault Reward &7(1000 Coins)"
      lore:
        - "&7Purchase this to receive a diamond!"
        - ""
        - "&e&lBALANCE:"
        - "&6* &f%balance% MobCoins"
      material:
        name: "DIAMOND"
        durability: 0 # Most items will use a value of 0
      price: 1000
      slot: 0 # The first slot is always 0
      commands:
        - "give %player% diamond 1"