name: EternalMobCoins
version: ${project.version}
main: me.frost.mobcoins.MobCoins
authors: [ Frost ]
softdepend: [ PlaceholderAPI ]
commands:
  mobcoins:
    aliases: [ emobcoins, eternalmobcoins, transfer, etransfer, eternaltransfer, mobshop, emobshop, eternalmobshop ]